# **인공지능의 발전방향**

[![Open in Colab](http://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/thekimk/All-About-Deep-Learning/blob/main/Lecture4-1_DeepLearning_HistoryAI_KK.ipynb)

<center><img src='Image/Expert/MachineLearning_Algorithms.png' width='1000'>(https://cloud.tencent.com/developer/article/1071285)</center>  

> **"`빅데이터에 인공지능이 결합`되어 혁신적으로 빠르게 의사결정하는 `디지털시대`를 우리는 여전히 체감하기 어려움**
>
> **(1) `빅데이터와 인공지능은 만능이다`라는 환상을 가진 사람**   
>
> **(2) 열정적으로 공부는 하고 있는데, `기대에 떨어지는 현재의 수준과 한계점`에 혼란인 사람**
>
> <span style="color:red">$\Rightarrow$ **"`보통사람들을 위한 가이드`로 가능한 쉽게 설명하는데 중점"**</span>

---

**1) 인공지능이란(Artificial Intelligence, AI)?:** `인간지능의 원리`를 찾기위한 목적으로, `프로그래밍으로 인공적 구현`하는 대상

- `1956년 처음 등장`한 이래 `아직도 미래기술로써 인식`되는 인공지능
- 새롭게 지능의 원리가 발견하면, 더이상 지능으로 간주되지 않고 `일반적 사실로 인식되는 과학적 프레임워크` 기반으로 생성
- **AI Effect:** 발견된 원리 또는 사실을 제외하고 `아직 발견하지 못한 새로운 지능의 비결을 꾸준히 찾는 것`

---

**2) 아이디어:** `규칙은 끊임없이 변하기 때문에` 사람이 규칙을 일일이 찾는 것은 좋은 접근이 아니고, 기존 입출력 데이터 기반으로 `기계가 스스로 관계성 규칙을 지속적으로 찾아내도록` 유도하자

- 전체적으로 `지도학습/비지도학습/강화학습`이라는 3가지 종류의 알고리즘으로 해결중

<center><img src='Image/Expert/ML_Type_CategoryKorean.png' width='800'></center>

| **알고리즘 종류** | **학습 방향** |
|:---:|---|
| **지도학습 알고리즘** | 기계에게 `문제와 답을 학습`시킨 후 향후 답을 예측 |
| **비지도학습 알고리즘** | 기계에게 `문제만 학습`시킨 후 스스로 패턴을 고려하여 답을 예측 |
| **강화학습 알고리즘** | 아무것도 모른채 `일단 실전`에 뛰어들어 `시행착오로 학습`하고 스스로 개선시켜 향후 답을 예측<br>데이터와 상호작용을 반복하기에 `시간이 오래걸리나 가장 강력하고 진보적`인 방법 |

---

- 각 알고리즘은 인간이 해결하고 싶어하는 `특정 세부문제 맞춤해결` 방식으로 진화중

| **알고리즘 종류** | **해결문제 종류** | **해결 예시** |
|:---:|:---:|:---|
| **지도학습 알고리즘** | **예측문제** | 주관식 문제의 숫자형태의 정답을 해결 |
|  | **분류문제** | 객관식 문제의 보기들 중 정답을 해결 |
| **비지도학습 알고리즘** | **군집문제** | 시험문제에 어떤 유형들이 있는지 해결 |
|  | **차원변환문제** | 시험문제의 풀이법을 다양한 관점으로 변환 |
| **강화학습 알고리즘** | **-** | 공교육/사교육 없이 스스로 지도학습/비지도학습 문제를 해결하고<br>오답노트도 스스로 만들고 학습하여 성적을 계속 끌어올림 |

<center><img src='Image/Expert/HumanLearningMachineLearning.png' width='800'>(루이, 다빈치랩스)</center>

---

- 인간이 해결하고 싶어하는 `문제에 맞게` 기계에게 `데이터를 학습`시키는 방식으로 진화되어 `데이터는 필수`

<center><img src='Image/Expert/ML_Type_Category.png' width='700'></center>
<center><img src='Image/Expert/ML_Type_Application_Upgrade.png' width='700'></center>
<center><img src='Image/Expert/AI_ML_DL.jpg' width='700'>(딥러닝을 통한 인공지능의 이해, 곽수하 / 컴공 조교수)</center>

---

**3) 알고리즘의발전:**

- **인공지능:** `인간의 지능`을 기계 등에 `인공적으로 구현`한 것으로, 인간의 지능을 모방하는 기계를 표현하는 `가장 광범위한 용어`로 음성 및 얼굴인식이나 의사결정 등 `인간이 그동안 해온 작업을 예측, 자동화 및 최적화하는데 사용`

> - **Weak AI:** `Artificial Narrow Intelligence(ANI)`라고도 하며 체스게임이나 사진 식별, 챗봇 등 `특정 Task에 특화된 AI`
> - **Strong AI(Weak):** `Artificial General Intelligence(AGI)`라고도 하며 `인간과 비등한능력을 가진 AI` 
> - **Strong AI:** `Artificial Super Intelligence(ASI)`라고도 하며 `인간의 지능과 능력을 넘어서는 AI`

- **머신러닝:** `인공지능의 한 분야`로 컴퓨터가 학습할 수 있는 알고리즘과 기술을 개발하는 분야를 의미하며, 사람이 특징을 알려주면 `기계가 명시적으로 프로그래밍 되지 않은 동작을 스스로 학습해 수행`하는데 사용되고 `스몰데이터에서 딥러닝보다 잘하는 편`
- **딥러닝:** 비선형 조합을 통해 `높은 수준의 패턴학습을 시도하는 머신러닝` 알고리즘으로, 머신러닝에서의 `많은 특징 추출 작업을 자동화`하고 신경망을 이용하여 `인간의 신경계와 유사한 구조로 여러 분야에서 높은 성능으로 분석`

<center>"Evolution of Artificial Intelligence"<img src='Image/Expert/DL_Evolution.png' width='600'></center>

> - 인공신경망(딥러닝)은 머신러닝 방법론 중 하나로 `1950년대 처음 제안`
> - 80~90년대에 널리 사용되다 `계산 비용이 높아 90년대 후반에 약세`
> - 2000년대 이후 `빅데이터 + 컴퓨팅파워 + 알고리즘 고도화로 재부상`
> - 인공신경망의 한계는 결국 `최적화가 어렵고 너무 많은 시간이 소요`된다는 점
> - 인공신경망의 알고리즘을 개선하며 `비지도 학습을 통해 최적화를 수행하는 방식`으로 한계 극복 및 가능성 확장

# **딥러닝의 시초 인공신경망의 등장(1940~1950)**

## 인간 뇌의 비밀

> **"인간은 어떻게 `동물과 다른 창의적 사고`가 가능할까?"**
>
> **"아인슈타인은 `어떤 뇌`를 통해 시공간의 비밀을 알 수 있었을까?"**
>
> **"보통 사람은 왜 아인슈타인의 `천재적 사고가 어려울까?`"**

---

**1) 뇌의 구조를 모방한 퍼셉트론(Perceptron):**

<span style="color:red">$\Rightarrow$ **"과학자들이 뇌의 구조를 분석하여 `1000억개 가량의 뉴런(Neuron)이라는 신경세포가 다른 신경세포들과 100조개 가량의 가지로 연결되어 화학적 신호를 주고받는`다는 사실을 밝혀내고 이해하고 있음"**</span>

<center><img src='Image/Expert/DL_Neuron.png' width='600'></center>

- `뇌의 구조와 동작을 완벽하게 재현`할 수 있다면 인간 뇌와 유사한 `인공뇌(Artificial Brain)`를 만들 수 있지만 `현재 기술로는 구현이 어려운` 실정
- 대신 `뉴런을 대신하는 프로그래밍 함수`와 화학적 신호로 전달하는 `물질을 대신하는 숫자 데이터`는 프로그램으로 충분히 구현 가능하고 이를 `퍼셉트론(Perceptron)`이라고 함

---

**2) 퍼셉트론의 역할과 딥러닝:**

- 인간의 뇌는 입력 데이터를 단순히 하나의 뉴런을 흉내낸 퍼셉트론만 거치는 것이 아니라 `숨겨진 층의 뉴런들을 거쳐서 최종 출력으로` 바꿈

<center><img src='Image/Expert/DL_MLP_Custom.PNG' width='500'></center>

- 이를 더욱 복잡하게 쌓아서 만들면 `깊은 신경구조`가 될 것이고 `인공뇌 또는 인공신경망 구현이 가능`할 수 있을 것이며 더욱 복잡한 일들을 해결할 수 있을 것이란 기대에 등장한 것이 `딥러닝(Deep Learning)`이라는 머신러닝 알고리즘

<center><img src='Image/Expert/Human_vs_AI.JPG' width='700'>(으뜸 데이터분석과 머신러닝, 생능출판)</center>

---

**3) 인공신경망(Artificial Neural Network: ANN)**

> - `인간 뇌의 신경구조`를 네트워크로 표현할 수 있다고 최초로 제안 (McCulloch and Pitts, 1943)
> - `인간 두뇌의 신경세포를 모방한 컴퓨터 알고리즘 네트워크` 구조를 의미 
> - `인간의 뇌`는 많은 신경들이 존재하지만 함께 작동하여 마치 `하나의 학습 알고리즘`으로 여러가지를 동시에 학습하고 해결
> - 마찬가지로 `수천개의 모델이나 프로그램` 대신에 `하나의 학습 알고리즘`을 목표로 접근
> - `어떠한 형태의 규칙/함수/가설`도 쉽게 근사할 수 있는 `Universal Function Approximator`를 목표

---

**4) 뉴런과 인공신경망 비교 정리:**

- **뉴런의 입출력:**

<center><img src='Image/Expert/DL_Neuron.png' width='600'></center>

- **인공신경망의 입출력:**

<center><img src='Image/Expert/DL_ANN.png' width='600'></center>

> **(1) 동그라미:** 하나의 `노드(뉴런)`
>
> **(2) 실선:** 노드와 노드가 이어진 `전달선(빨간색선)`  
>
> - 인간의 뇌는 `뉴런들이 신호/자극(Input)`을 받고 그 자극이 `임계값(Weight)을 넘으면 신호를 전달(Output)`하는 과정

## **단순한 퍼셉트론의 구조:** 단층퍼셉트론

> **"여러개의 노드(뉴런)들로 이루어진 `하나의 인공신경망(단일층)`으로 구성된 알고리즘 (Rosenblatt, 1958)"**
>
> - 모델의 층 갯수를 셀 때 `보통 입력층을 생략하므로 1개 출력층이 존재하는 단층 퍼셉트론`

<center><img src='Image/Expert/DL_ANN.png' width='600'></center>

<!-- <center><img src='Image/Expert/DL_Comparing1.PNG' width='200'></center> -->

---

**1) 구조와 용어:**

- 데이터가 각 노드에 입력되고 `연결강도(가중치)`를 곱한다음 합산하여 전달하며 최종적으로 `하나의 값(분류 or 연속)으로 출력`
- 현재의 딥러닝도 이러한 구조를 `여러개의 레이어층으로 확장`했을 뿐 같은 구조이며 `인공뇌 개발을 기대`하게 됨

> **(1) 입력층(Input Layer):** 데이터가 `입력되는 노드`
>
> **(2) 가중치(Weight):** 입력 데이터 각각이 `출력에 영향을 주는 정도`인 가중치(Parameter) 연결선
>
> **(3) 출력층(Output Layer):** 해결하고자 하는 문제에 맞춰 `최종 출력값을 반환`하는 역할
>
> **(3') 활성함수(Activation Function):** 출력값을 모두 반영하지 않고 `특정 수준의 데이터만 필터/제한/변환`하는 역할
> 
> - 정해진 `임계값 기준` 은닉층의 출력을 `최종적으로 원하는 출력값으로 변환`
> - `비선형 Scaling`과 유사하며 일반적으로 `일정 수준이 넘는 데이터를 전달`
> - `비용함수의 책임 또는 영향을 각 가중치 별 추정(미분)`가능하도록 반영하는 도구
>
> $$
\begin{aligned}
W_1 &:= W_0 - \alpha \frac{\partial}{\partial w} \left[ \text{Cost Function} \right] \\ &= W_0 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_0} \\
W_2 &:= W_1 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_1} \\
W_3 &:= W_2 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_2} \\
& \vdots \\
W &:= W - \alpha \frac{\partial C(W)}{\partial W}
\end{aligned}
$$

---

**2) 지도학습 회귀 및 분류문제의 단층퍼셉트론 표현:**

- **회귀문제의 신경망:**

<center><img src='Image/Expert/DL_Comparing1.PNG' width='200'></center>

- **분류문제의 신경망:**

<center><img src='Image/Expert/DL_Classification.png' width='350'></center>

## **지도학습의 간단한 인공신경망 생성**

In [1]:
# 회귀문제
# 입력 X
import numpy as np
X = np.array([1, 2, 3, 4, 5])

# 가중치 W
W = np.array([0.5, 0.6, 0.1, 0.3, 0.2])

# 출력 Y
Y = np.sum(W * X)
Y

4.2

In [2]:
# 분류문제
# 입력 X
import numpy as np
X = np.array([1, 2, 3, 4, 5])

# 가중치 W
W = np.array([0.5, 0.6, 0.1, 0.3, 0.2])

# 출력 Y
Y = np.sum(W * X)

# 비선형 activation
def activation(x):
    return 1 / (1 + np.exp(-x))

activation(Y)

0.9852259683067269

- `은닉층 없이 출력층만 존재하는 인공신경망`:

<center><img src='Image/Expert/DL_Comparing1.PNG' width='200'></center>

$$
\begin{aligned}
W &= \left[ w_1, w_2, w_3, w_4, w_5 \right], \\
X &= \left[ X_1, X_2, X_3, X_4, X_5 \right], \\
Y &= W * X \\
&= w_1 X_1 + w_2 X_2 + w_3 X_3 + w_4 X_4 + w_5 X_5 ~~~ (\text{Linear Regression)}\\
&= w_0 + w_1 X_1 + w_2 X_2 + w_3 X_3 + w_4 X_4 + w_5 X_5 ~~~ (\text{Linear Regression with Constant)}\\
&= \sigma (w_1 X_1 + w_2 X_2 + w_3 X_3 + w_4 X_4 + w_5 X_5) ~~~ (\text{Logistic Regression)}\\
&= \sigma (w_0 + w_1 X_1 + w_2 X_2 + w_3 X_3 + w_4 X_4 + w_5 X_5) ~~~ (\text{Logistic Regression with Constant)}\\
\end{aligned}
$$

In [3]:
# 만약에 노드가 3개인 은닉층이 추가된다면???
# 입력 X
import numpy as np
X = np.array([1, 2, 3, 4, 5])

# 가중치 W
W = np.array([[0.5, 0.6, 0.1, 0.3, 0.2], [0.2, 0.1, 0.8, 0.2, 0.1], [0.3, 0.1, 0.1, 0.2, 0.7]])

# 출력 Y
Y = np.sum(W * X)
Y

13.400000000000002

- `노드가 3개인 은닉층이 추가된 인공신경망`:

<center><img src='Image/Expert/DL_Comparing2.PNG' width='350'></center>

$$
\begin{aligned}
W &= \begin{bmatrix} 
   w_{11} & w_{12} & w_{13} & w_{14} & w_{15}  \\
   w_{21} & w_{22} & w_{23} & w_{24} & w_{25}  \\
   w_{31} & w_{32} & w_{33} & w_{34} & w_{35}  \\
\end{bmatrix}, \\
X &= \left[ X_1, X_2, X_3, X_4, X_5 \right], \\
Y &= W * X ~~~ (\text{Linear Regression}) \\
&= w_{10} + w_{11} X_1 + w_{12} X_2 + w_{13} X_3 + w_{14} X_4 + w_{15} X_5 ~~~ (\text{First Neuron}) \\
&+ w_{10} + w_{21} X_1 + w_{22} X_2 + w_{23} X_3 + w_{24} X_4 + w_{25} X_5 ~~~ (\text{Second Neuron}) \\
&+ w_{10} + w_{31} X_1 + w_{32} X_2 + w_{33} X_3 + w_{34} X_4 + w_{35} X_5 ~~~ (\text{Third Neuron}) \\
\end{aligned}
$$

---

- 인공신경망은 `하나의 층에 수백개의 입력값과 가중치 존재` 가능
- **행렬:** 이러한 상황을 표현하는 `강력한 수학 표현`
- **선형대수:** `행렬을 다루는 수학`의 한 분야

In [4]:
# 가중치를 변경하면 뉴런의 값 또는 기능이 변경됨
# 입력 X
import numpy as np
X = np.array([1, 2, 3, 4, 5])

# 가중치 W
W = np.array([[0.5, 0.6, 0.1, 0.3, 0.5], [0.2, 0.1, 0.8, 0.2, 0.5], [0.3, 0.1, 0.1, 0.2, 0.5]])

# 출력 Y
Y = np.sum(W * X)
Y

15.900000000000002

## 퍼셉트론의 한계(AI Winter)와 학습?

> **"앞선 예시는 데이터의 학습과정이 없는 우리가 입력한 가중치 적용하였고, `가중치를 스스로 찾도록 학습하려면 어떻게?`"**

---

**1) 배경:**

- 도널드 올딩 헵은 뉴런의 작동원리를 연구하다가 `서로 반복적 지속적으로 영향을 주고받는 뉴런들은 함께 활성화/비활성화되어 연결의 강도(두께)가 높아/낮아진다 (1949년)`는 사실을 발견하였고 이를 인공지능의 `가중치(Weight)를 학습하는 아이디어`의 토대가 됨

- **헵의 학습 법칙(Hebbian Learning Rule):** `퍼셉트론 학습의 근거`로 목표치를 만족시키도록 `뉴런에 가해지는 입력(x)과 출력(y)을 업데이트`

$$
\begin{aligned}
W_{xy}^{k+1} &:= W_{xy}^{k} + y^k x^k \\
\end{aligned}
$$

---

**2) 발전:**

- 헵의 이론은 완벽하지 않았지만 `시간이 흐르며 계속 수정 및 확장되어 여전히 타당한 주장`으로 받아들여 지고 있음
- `알고리즘의 출력`($\hat{y}$)`이 목표값`($y$)`과 일치하는지 확인`하여 일치하면 가중치가 변경되지 않음

$$
\begin{aligned}
W_{xy}^{k+1} &:= W_{xy}^{k} + y^k x^k \\
& \Downarrow \\
W_{xy}^{k+1} &:= W_{xy}^{k} + (y^k - \hat{y}^k) x^k \\
\end{aligned}
$$

| **목표값** | **출력값** | **$$y^k - \hat{y}^k$$** | **가중치 업데이트 방향** |
|:---:|:---:|:---:|:---:|
| 1 | 1 | 0 | 업데이트 안함 |
| -1 | -1 | 0 | 업데이트 안함 |
| 1 | -1 | 2 | 양의 방향 |
| -1 | 1 | -2 | 음의 방향 |

- 정답과 일치하지 않으면 가중치를 변경하는데 `학습률`($\alpha$)을 통해 너무 급격히 변경되는 것을 방지

$$
\begin{aligned}
W_{xy}^{k+1} &:= W_{xy}^{k} + (y^k - \hat{y}^k) x^k \\
& \Downarrow \\
W_{xy}^{k+1} &:= W_{xy}^{k} + \alpha (y^k - \hat{y}^k) x^k \\
& \Downarrow \\
W_1 &:= W_0 - \alpha \frac{\partial}{\partial w} \left[ \text{Cost Function} \right] \\ &= W_0 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_0} \\
W_2 &:= W_1 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_1} \\
W_3 &:= W_2 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_2} \\
& \vdots \\
W &:= W - \alpha \frac{\partial C(W)}{\partial W}
\end{aligned}
$$

In [5]:
# 퍼셉트론을 학습시키는 알고리즘을 만들어서 가중치 업데이트
# 학습률이 없는 경우 비용함수의 변화가 커서 가중치의 변화가 불가 또는 급격한 변화
# 데이터 로딩
import pandas as pd
df = pd.DataFrame([[0, -1, -1, 1], 
                   [0, -1, 1, 1], 
                   [1, 1, -1, 1], 
                   [1, 1, 1, 1],
                   [0, -1, 1, 1],
                   [1, 1, 1, -1]],
                  columns=['Y', 'X1', 'X2', 'X3'])
display(df)

# 입력 X
X = df[['X1', 'X2', 'X3']].values

# 출력 Y
Y = df['Y'].values

# 비선형 activation
def activation(x):
    return 1 / (1 + np.exp(-x))

# 가중치 W
W = np.array([0 for i in range(X.shape[1])])
print('initial W: ', W)

# 가중치 업데이트
def training(X, Y, learning_rate=1):
    global W
    for i in range(X.shape[0]):
        Y_pred = activation(np.sum(W * X[i]))
        error = Y[i] - Y_pred
        if error != 0:
            W = W + learning_rate * error * X[i]
            print('입력: ', X[i], '목표: ', Y[i], '출력: ', Y_pred, '\n',
                  'error: ', error, '업데이트된 가중치: ', W)
    return W

training(X, Y)

   Y  X1  X2  X3
0  0  -1  -1   1
1  0  -1   1   1
2  1   1  -1   1
3  1   1   1   1
4  0  -1   1   1
5  1   1   1  -1

initial W:  [0 0 0]
입력:  [-1 -1  1] 목표:  0 출력:  0.5
 error:  -0.5 업데이트된 가중치:  [ 0.5  0.5 -0.5]
입력:  [-1  1  1] 목표:  0 출력:  0.3775406687981454
 error:  -0.3775406687981454 업데이트된 가중치:  [ 0.87754067  0.12245933 -0.87754067]
입력:  [ 1 -1  1] 목표:  1 출력:  0.469423368982364
 error:  0.5305766310176361 업데이트된 가중치:  [ 1.4081173  -0.4081173  -0.34696404]
입력:  [1 1 1] 목표:  1 출력:  0.6576942833339211
 error:  0.3423057166660789 업데이트된 가중치:  [ 1.75042302 -0.06581158 -0.00465832]
입력:  [-1  1  1] 목표:  0 출력:  0.1393267640463281
 error:  -0.1393267640463281 업데이트된 가중치:  [ 1.88974978 -0.20513835 -0.14398509]
입력:  [ 1  1 -1] 목표:  1 출력:  0.8615944473420812
 error:  0.13840555265791876 업데이트된 가중치:  [ 2.02815533 -0.06673279 -0.28239064]

array([ 2.02815533, -0.06673279, -0.28239064])

In [6]:
# 퍼셉트론을 학습시키는 알고리즘을 만들어서 가중치 업데이트
# 학습률을 통해 비용함수의 변화를 줄여서 가중치의 변화를 미세조정! -> 그럼에도 수렴속도에 대해선 불만족
# 데이터 로딩
import pandas as pd
df = pd.DataFrame([[0, -1, -1, 1], 
                   [0, -1, 1, 1], 
                   [1, 1, -1, 1], 
                   [1, 1, 1, 1],
                   [0, -1, 1, 1],
                   [1, 1, 1, -1]],
                  columns=['Y', 'X1', 'X2', 'X3'])
display(df)

# 입력 X
X = df[['X1', 'X2', 'X3']].values

# 출력 Y
Y = df['Y'].values

# 비선형 activation
def activation(x):
    return 1 / (1 + np.exp(-x))

# 가중치 W
W = np.array([0 for i in range(X.shape[1])])
print('initial W: ', W)

# 가중치 업데이트
def training(X, Y, learning_rate=0.01):
    global W
    for i in range(X.shape[0]):
        Y_pred = activation(np.sum(W * X[i]))
        error = Y[i] - Y_pred
        if error != 0:
            W = W + learning_rate * error * X[i]
            print('입력: ', X[i], '목표: ', Y[i], '출력: ', Y_pred, '\n',
                  'error: ', error, '업데이트된 가중치: ', W)
    return W

training(X, Y)

   Y  X1  X2  X3
0  0  -1  -1   1
1  0  -1   1   1
2  1   1  -1   1
3  1   1   1   1
4  0  -1   1   1
5  1   1   1  -1

initial W:  [0 0 0]
입력:  [-1 -1  1] 목표:  0 출력:  0.5
 error:  -0.5 업데이트된 가중치:  [ 0.005  0.005 -0.005]
입력:  [-1  1  1] 목표:  0 출력:  0.49875000260416025
 error:  -0.49875000260416025 업데이트된 가중치:  [ 9.98750003e-03  1.24999740e-05 -9.98750003e-03]
입력:  [ 1 -1  1] 목표:  1 출력:  0.49999687500651047
 error:  0.5000031249934895 업데이트된 가중치:  [ 0.01498753 -0.00498753 -0.00498747]
입력:  [1 1 1] 목표:  1 출력:  0.5012531301821841
 error:  0.4987468698178159 업데이트된 가중치:  [ 1.99750000e-02 -6.25777983e-08 -7.79285482e-11]
입력:  [-1  1  1] 목표:  0 출력:  0.49500640037991417
 error:  -0.49500640037991417 업데이트된 가중치:  [ 0.02492506 -0.00495013 -0.00495006]
입력:  [ 1  1 -1] 목표:  1 출력:  0.506230927789578
 error:  0.493769072210422 업데이트된 가중치:  [ 2.98627547e-02 -1.24358595e-05 -9.88775480e-03]

array([ 2.98627547e-02, -1.24358595e-05, -9.88775480e-03])

In [7]:
# 퍼셉트론을 학습시키는 알고리즘을 만들어서 가중치 업데이트
# 학습률을 통해 가중치의 변화가 가능해짐! + 수렴속도 향상을 위해 MSE 활용 계기 -> 그럼에도 아쉽다면?
# 데이터 로딩
import pandas as pd
df = pd.DataFrame([[0, -1, -1, 1], 
                   [0, -1, 1, 1], 
                   [1, 1, -1, 1], 
                   [1, 1, 1, 1],
                   [0, -1, 1, 1],
                   [1, 1, 1, -1]],
                  columns=['Y', 'X1', 'X2', 'X3'])
display(df)

# 입력 X
X = df[['X1', 'X2', 'X3']].values

# 출력 Y
Y = df['Y'].values

# 비선형 activation
def activation(x):
    return 1 / (1 + np.exp(-x))

# 가중치 W
W = np.array([0 for i in range(X.shape[1])])
print('initial W: ', W)

# 가중치 업데이트
def training(X, Y, learning_rate=0.01):
    global W
    for i in range(X.shape[0]):
        Y_pred = activation(np.sum(W * X[i]))
        error = (Y[i] - Y_pred)**2
        if error != 0:
            W = W + learning_rate * error * X[i]
            print('입력: ', X[i], '목표: ', Y[i], '출력: ', Y_pred, '\n',
                  'error: ', error, '업데이트된 가중치: ', W)
    return W

training(X, Y)

   Y  X1  X2  X3
0  0  -1  -1   1
1  0  -1   1   1
2  1   1  -1   1
3  1   1   1   1
4  0  -1   1   1
5  1   1   1  -1

initial W:  [0 0 0]
입력:  [-1 -1  1] 목표:  0 출력:  0.5
 error:  0.25 업데이트된 가중치:  [-0.0025 -0.0025  0.0025]
입력:  [-1  1  1] 목표:  0 출력:  0.5006249996744794
 error:  0.2506253902990725 업데이트된 가중치:  [-5.00625390e-03  6.25390299e-06  5.00625390e-03]
입력:  [ 1 -1  1] 목표:  1 출력:  0.4999984365242523
 error:  0.2500015634781922 업데이트된 가중치:  [-0.00250624 -0.00249376  0.00750627]
입력:  [1 1 1] 목표:  1 출력:  0.5006265670564674
 error:  0.24937382552980888 업데이트된 가중치:  [-1.25000129e-05 -2.34764931e-08  1.00000078e-02]
입력:  [-1  1  1] 목표:  0 출력:  0.5025031001711239
 error:  0.25250936568159055 업데이트된 가중치:  [-0.00253759  0.00252507  0.0125251 ]
입력:  [ 1  1 -1] 목표:  1 출력:  0.49686563482317425
 error:  0.25314418942188743 업데이트된 가중치:  [-6.15177551e-06  5.05651207e-03  9.99365956e-03]

array([-6.15177551e-06,  5.05651207e-03,  9.99365956e-03])

**3) Others:** 굳이 데이터를 `1번만 학습할 필요가 있을까?`

> **(1) Epoch:** 훈련데이터의 `알고리즘 학습 횟수`
>
> **(2) Batch:** `1 epoch`에서 학습과 평가를 진행할 `row 샘플의 갯수`
>
> <center><img src='Image/Expert/Batch_Epoch.png' width='500'>(https://www.baeldung.com/cs/epoch-neural-networks)</center>  
>
> - **Stochastic Gradient Descent:** `Batch Size = 1`
> - **Batch Gradient Descent:** `Batch Size = Size of Training Set`
> - **Mini-Batch Gradient Descent:** `1 < Batch Size < Size of Training Set`

In [8]:
# 퍼셉트론을 학습시키는 알고리즘을 만들어서 가중치 업데이트
# 오차의 variance를 줄이기 위해 batch를 증가!

# 데이터 로딩
import pandas as pd
df = pd.DataFrame([[0, -1, -1, 1], 
                   [0, -1, 1, 1], 
                   [1, 1, -1, 1], 
                   [1, 1, 1, 1],
                   [0, -1, 1, 1],
                   [1, 1, 1, -1]],
                  columns=['Y', 'X1', 'X2', 'X3'])
display(df)

# 입력 X
X = df[['X1', 'X2', 'X3']].values

# 출력 Y
Y = df['Y'].values

# 비선형 activation
def activation(x):
    return 1 / (1 + np.exp(-x))

# 가중치 W
W = np.array([0 for i in range(X.shape[1])])
print('initial W: ', W, '\n')

# 가중치 업데이트
def training(X, Y, learning_rate=0.1, epochs=10):
    global W
    for i in range(0, X.shape[0], 2):
        Y_pred = activation(np.sum(W * X[i:i+2]))
        error = (Y[i] - Y_pred)**2
        if error != 0:
            W = W + learning_rate * error * X[i]
        print('입력: ', X[i], '목표: ', Y[i], '출력: ', Y_pred, '\n',
              'error: ', error, '업데이트된 가중치: ', W)
    print('')
    return W

W = training(X, Y, epochs=100)
W

   Y  X1  X2  X3
0  0  -1  -1   1
1  0  -1   1   1
2  1   1  -1   1
3  1   1   1   1
4  0  -1   1   1
5  1   1   1  -1

initial W:  [0 0 0]

입력:  [-1 -1  1] 목표:  0 출력:  0.5
 error:  0.25 업데이트된 가중치:  [-0.025 -0.025  0.025]
입력:  [ 1 -1  1] 목표:  1 출력:  0.5
 error:  0.25 업데이트된 가중치:  [ 0.   -0.05  0.05]
입력:  [-1  1  1] 목표:  0 출력:  0.47502081252106
 error:  0.22564477232816801 업데이트된 가중치:  [-0.02256448 -0.02743552  0.07256448]

array([-0.02256448, -0.02743552,  0.07256448])

In [9]:
# 퍼셉트론을 학습시키는 알고리즘을 만들어서 가중치 업데이트
# 오차의 bias를 줄이기 위해 epoch를 증가!

# 데이터 로딩
import pandas as pd
df = pd.DataFrame([[0, -1, -1, 1], 
                   [0, -1, 1, 1], 
                   [1, 1, -1, 1], 
                   [1, 1, 1, 1],
                   [0, -1, 1, 1],
                   [1, 1, 1, -1]],
                  columns=['Y', 'X1', 'X2', 'X3'])
display(df)

# 입력 X
X = df[['X1', 'X2', 'X3']].values

# 출력 Y
Y = df['Y'].values

# 비선형 activation
def activation(x):
    return 1 / (1 + np.exp(-x))

# 가중치 W
W = np.array([0 for i in range(X.shape[1])])
print('initial W: ', W, '\n')

# 가중치 업데이트
def training(X, Y, learning_rate=0.1, epochs=10):
    global W
    #####
    for e in range(epochs):
        print('epoch = ', e, '\n===================================')
    #####
        for i in range(0, X.shape[0], 2):
            Y_pred = activation(np.sum(W * X[i:i+2]))
            error = (Y[i] - Y_pred)**2
            if error != 0:
                W = W + learning_rate * error * X[i]
            print('입력: ', X[i], '목표: ', Y[i], '출력: ', Y_pred, '\n',
                  'error: ', error, '업데이트된 가중치: ', W)
        print('')
    return W

W = training(X, Y, epochs=20)
W

   Y  X1  X2  X3
0  0  -1  -1   1
1  0  -1   1   1
2  1   1  -1   1
3  1   1   1   1
4  0  -1   1   1
5  1   1   1  -1

initial W:  [0 0 0]

epoch =  0
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.5
 error:  0.25 업데이트된 가중치:  [-0.025 -0.025  0.025]
입력:  [ 1 -1  1] 목표:  1 출력:  0.5
 error:  0.25 업데이트된 가중치:  [ 0.   -0.05  0.05]
입력:  [-1  1  1] 목표:  0 출력:  0.47502081252106
 error:  0.22564477232816801 업데이트된 가중치:  [-0.02256448 -0.02743552  0.07256448]

epoch =  1
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.5474215161713972
 error:  0.29967031636739133 업데이트된 가중치:  [-0.05253151 -0.05740255  0.10253151]
입력:  [ 1 -1  1] 목표:  1 출력:  0.52497918747894
 error:  0.22564477232816801 업데이트된 가중치:  [-0.02996703 -0.07996703  0.12509599]
입력:  [-1  1  1] 목표:  0 출력:  0.46010149461890504
 error:  0.2116933853505503 업데이트된 가중치:  [-0.05113637 -0.05879769  0.14626532]

epoch =  2
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.597438480807236
 error:  0.35693273834925815 업데이트된 가중치:  [-0.08682964 -0.09449097  0.1819586 ]
입력:  [ 1 -1  1] 목표:  1 출력:  0.5474215161713972
 error:  0.20482728402459685 업데이트된 가중치:  [-0.06634692 -0.1149737   0.20244133]
입력:  [-1  1  1] 목표:  0 출력:  0.44276512535358187
 error:  0.19604095622937306 업데이트된 가중치:  [-0.08595101 -0.0953696   0.22204542]

epoch =  3
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.6493066411375191
 error:  0.42159911422528706 업데이트된 가중치:  [-0.12811092 -0.13752951  0.26420533]
입력:  [ 1 -1  1] 목표:  1 출력:  0.5676301785926848
 error:  0.18694366246379363 업데이트된 가중치:  [-0.10941656 -0.15622388  0.2828997 ]
입력:  [-1  1  1] 목표:  0 출력:  0.42251738241289666
 error:  0.17852093844104597 업데이트된 가중치:  [-0.12726865 -0.13837178  0.30075179]

epoch =  4
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.7018328193537772
 error:  0.49256930632207163 업데이트된 가중치:  [-0.17652558 -0.18762871  0.35000872]
입력:  [ 1 -1  1] 목표:  1 출력:  0.585881718745598
 error:  0.1714939508691 업데이트된 가중치:  [-0.15937619 -0.20477811  0.36715812]
입력:  [-1  1  1] 목표:  0 출력:  0.39901853639764134
 error:  0.15921579238891584 업데이트된 가중치:  [-0.17529777 -0.18885653  0.3830797 ]

epoch =  5
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.7533862929179165
 error:  0.5675909063566007 업데이트된 가중치:  [-0.23205686 -0.24561562  0.43983879]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6024212366177305
 error:  0.15806887309257464 업데이트된 가중치:  [-0.21624997 -0.26142251  0.45564568]
입력:  [-1  1  1] 목표:  0 출력:  0.3721872148195957
 error:  0.1385233228751679 업데이트된 가중치:  [-0.2301023  -0.24757018  0.46949801]

epoch =  6
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.8020570083341784
 error:  0.6432954446179723 업데이트된 가중치:  [-0.29443185 -0.31189972  0.53382755]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6174624449352557
 error:  0.14633498103491227 업데이트된 가중치:  [-0.27979835 -0.32653322  0.54846105]
입력:  [-1  1  1] 목표:  0 출력:  0.3422988559504652
 error:  0.11716850678499734 업데이트된 가중치:  [-0.2915152  -0.31481637  0.5601779 ]

epoch =  7
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.8459764748502901
 error:  0.7156761960001236 업데이트된 가중치:  [-0.36308282 -0.38638399  0.63174552]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6311900207742058
 error:  0.13602080077653073 업데이트된 가중치:  [-0.34948074 -0.39998607  0.6453476 ]
입력:  [-1  1  1] 목표:  0 출력:  0.31003147960757793
 error:  0.09611951834766401 업데이트된 가중치:  [-0.35909269 -0.39037412  0.65495955]

epoch =  8
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.8837164333227002
 error:  0.7809547345245945 업데이트된 가중치:  [-0.43718816 -0.46846959  0.73305503]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6437628448741892
 error:  0.12690491069213097 업데이트된 가중치:  [-0.42449767 -0.48116008  0.74574552]
입력:  [-1  1  1] 목표:  0 출력:  0.2764139007808623
 error:  0.07640464454489239 업데이트된 가중치:  [-0.43213814 -0.47351962  0.75338598]

epoch =  9
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9145927769642763
 error:  0.8364799476752265 업데이트된 가중치:  [-0.51578613 -0.55716761  0.83703398]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6553173975757721
 error:  0.11880609641393834 업데이트된 가중치:  [-0.50390552 -0.56904822  0.84891459]
입력:  [-1  1  1] 목표:  0 출력:  0.2426700283552689
 error:  0.05888874266194702 업데이트된 가중치:  [-0.5097944  -0.56315935  0.85480346]

epoch =  10
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.938727592484352
 error:  0.8812094928914677 업데이트된 가중치:  [-0.59791534 -0.65128029  0.94292441]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6659709604442551
 error:  0.11157539926653341 업데이트된 가중치:  [-0.5867578  -0.66243783  0.95408195]
입력:  [-1  1  1] 목표:  0 출력:  0.21000825282711091
 error:  0.04410346625549574 업데이트된 가중치:  [-0.59116815 -0.65802749  0.9584923 ]

epoch =  11
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.956864724049947
 error:  0.9155901001311814 업데이트된 가중치:  [-0.68272716 -0.7495865   1.05005131]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6758244783637557
 error:  0.10508976882813109 업데이트된 가중치:  [-0.67221818 -0.76009548  1.06056028]
입력:  [-1  1  1] 목표:  0 출력:  0.17943340273962222
 error:  0.032196346018719464 업데이트된 가중치:  [-0.67543782 -0.75687584  1.06377992]

epoch =  12
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9700679258406204
 error:  0.9410317807447234 업데이트된 가중치:  [-0.769541   -0.85097902  1.1578831 ]
입력:  [ 1 -1  1] 목표:  1 출력:  0.684965043505913
 error:  0.09924702381323126 업데이트된 가중치:  [-0.75961629 -0.86090372  1.1678078 ]
입력:  [-1  1  1] 목표:  0 출력:  0.1516385001873418
 error:  0.022994234739066456 업데이트된 가중치:  [-0.76191572 -0.8586043   1.17010722]

epoch =  13
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9794483018255363
 error:  0.9593189759489269 업데이트된 가중치:  [-0.85784762 -0.9545362   1.26603912]
입력:  [ 1 -1  1] 목표:  1 출력:  0.6934680144546655
 error:  0.09396185816236513 업데이트된 가중치:  [-0.84845143 -0.96393238  1.27543531]
입력:  [-1  1  1] 목표:  0 출력:  0.1269871071034865
 error:  0.016125725370512354 업데이트된 가중치:  [-0.850064   -0.96231981  1.27704788]

epoch =  14
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9859948189331074
 error:  0.9721857829629311 업데이트된 가중치:  [-0.94728258 -1.05953839  1.37426646]
입력:  [ 1 -1  1] 목표:  1 출력:  0.7013988062238795
 error:  0.08916267292452426 업데이트된 가중치:  [-0.93836631 -1.06845465  1.38318272]
입력:  [-1  1  1] 목표:  0 출력:  0.1055608501902159
 error:  0.011143093092881204 업데이트된 가중치:  [-0.93948062 -1.06734034  1.38429703]

epoch =  15
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9905059944468383
 error:  0.9811021250351201 업데이트된 가중치:  [-1.03759084 -1.16545056  1.48240725]
입력:  [ 1 -1  1] 목표:  1 출력:  0.7088143940795113
 error:  0.08478905709528214 업데이트된 가중치:  [-1.02911193 -1.17392946  1.49088615]
입력:  [-1  1  1] 목표:  0 출력:  0.08723610695551388
 error:  0.007610138356753858 업데이트된 가중치:  [-1.02987294 -1.17316845  1.49164717]

epoch =  16
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9935872916416065
 error:  0.9872157061117028 업데이트된 가중치:  [-1.12859451 -1.27189002  1.59036874]
입력:  [ 1 -1  1] 목표:  1 출력:  0.7157645737220124
 error:  0.08078977755142931 업데이트된 가중치:  [-1.12051554 -1.279969    1.59844771]
입력:  [-1  1  1] 목표:  0 출력:  0.07176167244287734
 error:  0.005149737631798821 업데이트된 가중치:  [-1.12103051 -1.27945402  1.59896269]

epoch =  17
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9956792079538578
 error:  0.9913770851516216 업데이트된 가중치:  [-1.22016822 -1.37859173  1.6981004 ]
입력:  [ 1 -1  1] 목표:  1 출력:  0.7222930166570698
 error:  0.07712116859743051 업데이트된 가중치:  [-1.2124561  -1.38630385  1.70581251]
입력:  [-1  1  1] 목표:  0 출력:  0.0588224788601829
 error:  0.0034600840192566644 업데이트된 가중치:  [-1.21280211 -1.38595784  1.70615852]

epoch =  18
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9970935762896245
 error:  0.9941955998780332 업데이트된 가중치:  [-1.31222167 -1.4853774   1.80557808]
입력:  [ 1 -1  1] 목표:  1 출력:  0.7284381546534898
 error:  0.07374583584800191 업데이트된 가중치:  [-1.30484709 -1.49275198  1.81295267]
입력:  [-1  1  1] 목표:  0 출력:  0.04808506859514437
 error:  0.0023121738217997396 업데이트된 가중치:  [-1.3050783  -1.49252077  1.81318388]

epoch =  19
===================================
입력:  [-1 -1  1] 목표:  0 출력:  0.9980471766964829
 error:  0.9960981669118206 업데이트된 가중치:  [-1.40468812 -1.59213058  1.9127937 ]
입력:  [ 1 -1  1] 목표:  1 출력:  0.7342339221386271
 error:  0.07063160814181729 업데이트된 가중치:  [-1.39762496 -1.59919374  1.91985686]
입력:  [-1  1  1] 목표:  0 출력:  0.039226449567109786
 error:  0.0015387143456410076 업데이트된 가중치:  [-1.39777883 -1.59903987  1.92001073]

array([-1.39777883, -1.59903987,  1.92001073])

In [10]:
# train 데이터 예측하기
def testing(W, X):
    if X.ndim == 2:
        return activation(np.sum(W * X, axis=1))
    else:
        return activation(np.sum(W * X))
    
testing(W, X)

array([0.99273092, 0.84796772, 0.89295356, 0.25411055, 0.84796772,
       0.00726908])

In [11]:
# test 데이터 예측하기
testing(W, np.array([1, 1, -1]))

0.007269083455060212

**4) 한계: 인공신경망의 `첫번째위기`**  

> **"`1958년 프랭크 로젠블랫`이 퍼셉트론 발표 당시 인공지능의 새로운 장으로 각광을 받았으나..."**
>
> **"인공지능 선구자 `마빈 민스크 교수가 한계에 대한 저서(Minskey and Papert, 1969)`를 발표하며 연구의 축소.."**
> - `단층퍼셉트론이 비선형을 분리할 수 없는 한계`를 수학적으로 증명
> - 퍼셉트론을 `학습시키는 알고리즘을 찾는 것이 매우 어려울 것`으로 예상

- 모든 데이터를 잘 분류하도록 학습하나 `선형분리 방식(직선으로 나눌수 있는 분류)`으로만 데이터 분류 가능
- 선형 분류는 가능하지만 좀더 성능좋은 `비선형 분류 접근 불가`
- `단층`이라 각 노드의 가중치를 변경할 수 없고 `초기에 주어진 가중치가 변경되지 않고 유지`
- 시작단계에서 가중치를 변경하여 분류결과를 변경이 가능하지만 `학습의 개념이 아닌 단순한 분류`문제 해결

<center><img src='Image/Expert/DL_SLP.png' width='500'></center>

- 간단한 `XOR 분류조차 할수 없는 수준`임이 밝혀지며 인기가 떨어짐

<center><img src='Image/Expert/DL_SLP_limit.gif' width='500'></center>
<!-- (http://ecee.colorado.edu/~ecen4831/lectures/NNet3.html) -->

# **단층퍼셉트론 문제의 해결(1960~1980)**

## 다층퍼셉트론(Multi-Layered Perceptron: MLP)

**1) 방향:** 인공신경망(단층퍼셉트론)의 `비선형성 접근 필요성`으로  `은닉층`을 반영한 `다층/심층신경망으로 딥러닝을 출발시킴`

- `2개의 직선` 또는 `여러개의 직선이 결합된 1개의 곡선`을 이용하여 제대로 분류가 가능할 것이라 가정
- `다층(여러개의 직선)신경망`으로 비선형 문제를 해결 (Hinton, 1986)  

<center><img src='Image/Expert/DL_Compare_MLP.jpg' width='500'></center>

- 여러문제가 해결되면서 `은닉층을 늘려 학습 결과를 향상`시키는 방법이 등장하며 `DNN(Deep Neural Network)`라고 함

<center><img src='Image/Expert/DL_ANN_MLP.bmp' width='600'>(https://4ir.kisti.re.kr/)</center>

- 은닉층의 수가 증가하면 더욱 어려운 문제를 풀수 있는데, 통상 `은닉층을 최소 2개이상 가진 알고리즘`을 `딥러닝(Deep Learning)` 알고리즘 이라고 함

<center><img src='Image/Expert/DL_MLP_Custom.PNG' width='500'></center>

- **구조 정리:**

> **(1) 입력층(Input Layer):** 데이터가 `입력되는 노드`
>
> **(2) 가중치(Weight):** 입력 데이터 각각이 `출력에 영향을 주는 정도`인 가중치(Parameter) 연결선
>
> **(3) 은닉층(Hidden Layer):** 뉴런수 만큼 입력 데이터의 `모든 가능한 연산을 실행하여 출력으로 전달`
>
> **(4) 출력층(Output Layer):** 해결하고자 하는 문제에 맞춰 `최종 출력값을 반환`하는 역할
>
> **(4') 활성함수(Activation Function):** 출력값을 모두 반영하지 않고 `특정 수준의 데이터만 필터/제한/변환`하는 역할

**2) 한계:** 층(Layer)의 수가 많아지면서 `늘어나는 Weights를 수동으로 학습하기에 한계`가 있기에 여전히 데이터 학습 불가

## 역전파(Back Propagation: BP)

> **"`역방향`으로 데이터 학습 `가중치의 오차를 전달`한다"**  
>
> - 민스키 교수는 데이터 학습이 매우 어려울 것으로 예상하였고,
> - 데이터를 효과적으로 학습시키기 위해선 결국 `각 가중치가 비용함수에 미치는 영향`을 계산해야
> - 가중치마다의 `비용함수 변화량`을 고층부터 저층 레이어까지 전달하며 계산할 수 있는 `역전파 알고리즘` 제안하면서 큰 진전 (Rumelhart, Hinton, and Williams, 1986)
> - 데이터 학습을 통해 `비용함수가 줄어드는 방향`으로 `가중치 업데이트`가 가능해짐

---

**1) 순전파와 역전파의 흐름:** 

> **(1) 순전파(Feedforward):** `초기값 또는 주어진 가중치`로 출력층의 값을 출력
>
> **(2) 비용함수 계산:** `출력값이 목표값과 얼마만큼 차이`가 나는지 계산
>
> - 순전파 과정에서 `가중치를 미세하게 변화`시키면 `비용함수가 미세하게 변화`
> - 가중치의 변화와 비용함수의 변화가 `선형관계`
> - 역으로 `비용함수를 미세하게 변화`시키면 `가중치도 미세하게 변화`되는 선형관계
> - 미세하게 변화한다는 뜻이 `수학적으로 미분`을 의미
>
> <center><img src='Image/Expert/DL_Feed_Back.png' width='600'>(https://blog.naver.com/samsjang/221033626685)</center>
>
> **(3) 역전파(Backpropagation):** 
>
> - `비용함수가 줄어드는 방향의 미세변화`에 따른 `각 가중치의 미세변화 계산`
> - 각각의 초기값 또는 주어진 가중치에서 `계산된 미세변화만큼 가중치 업데이트`
>> - 업데이트 되는 가중치 변화량은,
>> - 출력층에서 `비용함수 미분값` $\times$ `활성함수 미분값`과,
>> - 입력층에서 `입력값`을 결합시킨 정도
> - 가중치를 갱신시키며 최적의 가중치를 찾는 알고리즘을 `오차 역전파 알고리즘(Error Back Propagation)`
> - 상세 이해를 위해서는 `미분, 연쇄법칙, 편미분, 선형대수 등` 이해 필요
> - `비용함수의 책임 또는 영향`이 계산가능해지고 이를 모델의 `가중치 또는 파라미터`라고 함
> - 비용함수를 줄이는 방향으로 모델의 가중치/파라미터를 조정하는 것을 `최적화(Optimization) 또는 학습(Training)`라고 함
> - **하이퍼파라미터(Hyperparameter):** 이러한 파라미터를 찾기 위해 `학습 과정에 관여하는 조절변수들`

<!-- <center><img src='Image/Expert/DL_Backpropagation.png' width='500'></center> -->

---

**2) 데이터 학습방향:** 우리가 원하는 `비용함수가 최소`가 될때까지 지속 업데이트

<center><img src='Image/Expert/DL_MLP_Learning.PNG' width='600'></center>

> **(1) 네트워크 초기화:** `가중치의 초기값`이 필요하며 일반적으로 `무작위로 초기화` 됨   
>
> - 초기값이 모두 같으면 모든 노드들의 입력값에 동일 가중치가 반영되어 `같은 값이 출력되고` 역전파로 인해 `비용함수 변화량도 모두 동일`해지므로 다른값 필요   
>
> **(2) 순전파:** 초기화된 가중치들의 출력이 퍼셉트론을 거쳐 Output Layer에 도달
>
> - $\hat{Y}_{init} = f(\sum_{i}^{k} w_i x_i - \theta)$  
>
> **(3) 비용함수 평가:**
>
> - **회귀문제:** $MSE = \frac{1}{k} \sum_{i=1}^{k} (\hat{Y}_{init} - Y)^2$    
>
> - **분류문제:** $Cross Entropy = \sum_{i=1}^{k} \left[ - \color{red}{\hat{Y}_{init} log (Pr(\hat{Y}_{init}))} - \color{blue}{(1-\hat{Y}_{init}) log (1-Pr(\hat{Y}_{init}))} \right]$    
>
> **(4) 역전파:** `각 가중치 별 현재 비용함수에 미치는 영향` 계산 
>
> - $\frac{\delta E}{\delta w} = \frac{\delta}{\delta w} \frac{1}{k} \sum_{i=1}^{k} (\hat{Y}_{init} - Y)^2$  
>
> **(5) 가중치 업데이트:** 비용함수를 줄이는 방향으로 각 가중치 업데이트
>
> <center><img src='Image/Expert/DL_GD.PNG' width='400'></center>
>
>$$
\begin{aligned}
W_1 &:= W_0 - \alpha \frac{\partial}{\partial w} \left[ \text{Cost Function} \right] \\ &= W_0 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_0} \\
W_2 &:= W_1 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_1} \\
W_3 &:= W_2 - \alpha \frac{\partial C(W)}{\partial W} |_{W=W_2} \\
& \vdots \\
W &:= W - \alpha \frac{\partial C(W)}{\partial W}
\end{aligned}
$$
>
> $$W_i^{new} = W_i^{old} - \alpha \Delta W_i^{old} = W_i^{old} - \alpha \frac{\delta C}{\delta w_i}$$  
>
> - **$\alpha$:** `학습률(Learing Rate)`이 낮으면 추정이 느리고, 높으면 최적점을 벗어나 오차가 증가될 수 있음

## 다양한 활성화 함수(Activation Function)

> **"신경망은 입력값의 가중합을 그대로 내보내지 않고 `활성화 함수를 거쳐서 출력하는가?`"**

---

**1) 배경:**

- `은닉층 없이 출력층만 존재하는 인공신경망`:

$$
\begin{aligned}
W &= \left[ w_1, w_2, w_3, w_4, w_5 \right], \\
X &= \left[ X_1, X_2, X_3, X_4, X_5 \right], \\
Y &= W * X \\
&= w_0 + w_1 X_1 + w_2 X_2 + w_3 X_3 + w_4 X_4 + w_5 X_5 ~~~ (\text{Linear Regression with Constant)}\\
&= \sigma (w_0 + w_1 X_1 + w_2 X_2 + w_3 X_3 + w_4 X_4 + w_5 X_5) ~~~ (\text{Logistic Regression with Constant)}\\
\end{aligned}
$$

> - 각 층은 변수 $X$의 차수가 모두 1이라서 연산방식은 기본적으로`선형 함수` 기반 `선형분류기`

- `노드가 3개인 은닉층이 추가된 인공신경망`:

$$
\begin{aligned}
W &= \begin{bmatrix} 
   w_{11} & w_{12} & w_{13} & w_{14} & w_{15}  \\
   w_{21} & w_{22} & w_{23} & w_{24} & w_{25}  \\
   w_{31} & w_{32} & w_{33} & w_{34} & w_{35}  \\
\end{bmatrix}, \\
X &= \left[ X_1, X_2, X_3, X_4, X_5 \right], \\
Y &= W * X ~~~ (\text{Linear Regression}) \\
&= w_{10} + w_{11} X_1 + w_{12} X_2 + w_{13} X_3 + w_{14} X_4 + w_{15} X_5 ~~~ (\text{First Neuron}) \\
&+ w_{10} + w_{21} X_1 + w_{22} X_2 + w_{23} X_3 + w_{24} X_4 + w_{25} X_5 ~~~ (\text{Second Neuron}) \\
&+ w_{10} + w_{31} X_1 + w_{32} X_2 + w_{33} X_3 + w_{34} X_4 + w_{35} X_5 ~~~ (\text{Third Neuron}) \\
\end{aligned}
$$

> - 여러개의 층이 연결되더라도 `결국 하나의 선형분류기`이기에 비선형 방식 미반영
>
> <center><img src='Image/Expert/DL_Compare_MLP.jpg' width='500'></center>
>
> $$
\begin{aligned}
H_1 &= W * X = f_1(X) \\
H_2 &= W * X = f_1(X) \\
& \vdots \\
Y &= f_{100}(H_1, H_2, \cdots) \\
&= f_{n} ( f_{n-1} ( \cdots f_1 (X) \cdots )) \\
\end{aligned}
$$
> 
> - 각 은닉층은 `마치 변수 추출(Feature Engineering)과 유사한 기능`을 보이지만 `선형의 곱은 결국 선형`
> - 가중합 출력에 `비선형적 함수`를 직접적으로 적용(곱하여) 비선형값을 생성하고 이를 `활성화 함수`라고 함

---

**2) 다양한 종류의 활성화 함수:** 

- 초기 단층퍼셉트론은 `계단형 함수`를 사용했는데 `미세변화를 계산할 수 없는(미분 불가)` 이슈가 존재하여 `가중치 별 비용함수 책임추정 어려움`
- 계단함수 외 전통적으로 많이 사용되던 활성함수는 `로지스틱회귀분석에서 사용되던 Sigmoid 함수`

<center><img src='Image/Expert/DL_ActivationFunction_Type.png' width='700'></center>

# **딥러닝의 등장과 암흑기(1980~2000)**

**1) 딥러닝(Deep Learning: DL)**

> **"인공신경망의 은닉층이 깊어진 `다층구조(Deep)의 네트워크 구조` 알고리즘"**
>
> <center><img src='Image/Expert/DL_What-is-Deep-Learning.png' width='500'></center>
<!-- (https://www.michaelchimenti.com/2017/11/deep-neural-nets-software-2-0/) -->

| **장점** | **단점** |
|:-:|:-:|
|- `연속형 및 범주형 변수` 모두 분석 가능<br>- 입력 데이터의 `비선형 특성 학습` 가능<br>- 기계학습 알고리즘에 비해 `예측력 우수`<br>- `Feature Engineering 반영`<br>- `빅데이터`에서 성능은 계속 향상 | - 복잡한 신경망은 `작동 시간이 오래 걸리고 고사양 PC필요`<br>- 알고리즘의 결과 `출력값이 일정하지 않음(Not Robust)`<br>- 추정된 가중치를 `정확히 해석하기 어려움` |

---

**2) 한계: NN의 두번째위기** 

> **(1) `Vanishing Gradients`:** 
>
> <center><img src='Image/Expert/DNN_Process.PNG' width='700'>(https://www.inf.ufpr.br/todt/IAaplicada/CNN_Presentation.pdf)</center>
>
> <center><img src='Image/Expert/Vanishing_Gradient_Sigmoid.png' width='500'></center>
>
> - 활성화 함수의 `양끝의 값에서의 미세변화(미분)가 0에 가까워` 학습이 반복적으로 진행되면 결국 기울기가 0에 가까워 `학습이 안되고 성능 하락`
>
> - **순전파 이슈:** 전파될 때 계산량이 많아지지만 `전파되는 값의 크기가 점차 작아짐`
>
> - **역전파 이슈:** `비용함수 역시 전달되는 값이 작아져` 최적값이 아닌 곳에서 학습 중지
> 
> <center><img src='Image/Expert/Vanishing_Gradient.PNG' width='500'></center>

> **(2) Local Minimum:** 
>
> - 수학적으로 `명확한 추정이 아닌 알고리즘 최적화` 이기에 `진짜 최소값(Global Minimum)이 아니라` 국소 최소값(Local Minimum)에서의 결과일 수 있음
>
> - `초기값`에 따라 또는 `비용함수의 모양`에 따라 `다양한 국소 최소값의 결과` 출력 가능
>
> <center><img src='Image/Expert/DL_LocalMinimum.png' width='500'></center>

> **(3) Low Learning Time:** 
>
> - `학습률이 어느 정도 낮아야` 성능이 좋아질텐데 `연산량 급증의 시간과 비용이 너무 높음`
> - 연산량은 급증하는데 `당시 하드웨어에서는 큰 부담과 한계`
>
> <center><img src='Image/Expert/History_LimitHardware.png' width='500'></center>

> **(4) Curse of Dimensionality:** `(몸집만 크고 실속이 없는)빅데이터일수록 성능 하락`
>
> - 딥러닝은 추정해야할 `가중치/파라미터가 많아 그 이상의 빅데이터(샘플) 요구`
>
> - 빅데이터 시대에 `독립변수의 수는 증가되지만 실제 독립적인 변수는 적을 수 있고(다중공선성)` 또는 증가하는 데이터 변수/차원 대비 이를 `대표할 데이터 샘플수가 상대적으로 적어지는(Sparse) 현상`
>
> - `적은 데이터패턴`만 모델에 학습 및 과적합되며 `고차원(빅데이터)일 수록 점점 심해짐`
>
> - `과적합 문제 또는 차원의 저주`라고도 함
>
> <center><img src='Image/Expert/DataDensity.png' width='600'>(https://www.freecodecamp.org/news/the-curse-of-dimensionality-how-we-can-save-big-data-from-itself-d9fa0f872335/)</center>

# **머신러닝의 호황기(2000~2006)**

> **"2000년대, 신경망 알고리즘 한계가 미해결된 상태에서 `비선형 함수를 사용한 다양한 머신러닝 알고리즘들`이 대세"**

---

**1) Support Vector Machine:**

- `클래스를 구분하는 경계면`을 찾아 데이터의 클래스를 예측
- 신경망과 별개로 개발된 `지도학습 기반의 분류` 예측기법
- `오차의 최소화` 외에 클래스 사이의 `여백(Margin)을 최대화 하는 경계`를 찾는 것이 목표
- 구분 경계면이 직선이 아닌 경우 `커널을 사용하여 비선형 변형 데이터 학습`

<center><img src='Image/Expert/ML_SVM.png' width='500'></center>

---

**2) K Nearest Neighbors:**

- 분류 알고리즘의 일종으로 `분석가(사용자)가 정의하는 샘플수`($K$)에 따라 `데이터들의 실제값과의 거리를 기준`으로 입력값의 클래스를 예측하는 지도학습 기반의 예측기법

<center><img src='Image/Expert/ML_KNN.png' width='600'></center>

> - 데이터의 거리는 `Euclidean, Manhattan, Minkowski, Correlation 등의 방법`이 사용됨
>
>> - 입력이 연속형이면 대게 유클리디안 거리 사용
>> - 입력이 이산형이면 대게 해밍거리를 사용
>
> - 입력값에서 가장 가까운 K개의 실제값을 거리 탐색 후, 분류 문제면 다수 투표를 수행하고, 회귀 문제이면 평균 계산으로 입력값의 클래스 예측
> - 변수들은 Normalization으로 Scaling 하는 편
> - 샘플수($K$)는 통상 `데이터의 갯수` $\sqrt n$ `보다 작은 값`으로 `홀수를 사용`하는 편
> - 샘플수가 `너무 작으면` 노이즈 때문에 `High Variance 문제`가 생기고, 샘플수가 `너무 크면` 다른 클래스의 값들이 포함될 가능성이 높아 `High Bias 문제`가 생김

---

**3) 머신러닝의 한계:**

- 대부분 `지도학습 문제에 알고리즘 성능이 좋았고`, 실제 `현실문제 대부분은 Unlabeled 데이터`이기에 `비지도학습에 한계`

> - `인간의 뇌`는 스스로가 Unlabeled Data를 사용해서 학습하고 의사결정하는 `Unsupervised Learning`
> - 머신러닝/딥러닝의 현실은 아직 `Unsupervised Learning의 성능이 높지 않고 Supervised Learning에 집중`
> - 우리가 보유한 데이터는 `Unlabeled가 훨씬 많고 Labeled 데이터는 많지 않음`
> - `적은 Labeled 데이터로 딥러닝을 학습하면 단층퍼셉트론보다 성능이 떨어지는 경우 발생`

# **딥러닝으로 비지도학습 재조명(2006~2010)**

> **"`새로운 학습 방법이 개발`되면서 인공신경망이 다시 학계의 주목"**    
>
> **"Unsupervised Learning, `즉 Label이 없는 데이터로 미리 충분히 학습`한 후, 역전파 알고리즘으로 Supervised Learing 수행"**

---

**1) Restricted Boltzmann Machine(RBM):** Unlabeled Data로 `선학습 한 후 역전파를 통해 Supervised Learning 수행`하는 알고리즘

- `선학습법(Pre Training)`을 적용한 RBM 알고리즘을 발표 (Hinton et al. 2006)
- `군집화(Clustering)로 데이터의 노이즈를 감소`시키고 하위층들을 하나하나 최적화시키며 학습
- `최적의 학습 초기값을 지정`할 수 있는 계기
- `비지도학습`을 이용하면서 `MLP 약점의 많은 부분이 극복`
> - Unlabeled 데이터 사용가능하고 선학습으로 `Vanishing Gradient, Overfitting, Local Minimum 문제가 해결 가능`할 것이라 여겨짐 (Bengio, 2009)
- 실제 `아기`들은 단어/음/뜻/문장 등의 `정답을 전혀 모르는 상태`에서 스스로 각 문법들을 Unsupervised Learning하며 학습하고 그 후에 `정답으로 Supervised Learning`을 수행
- `선학습법`이라는 새로운 관점은 `여전히 비지도학습 문제해결의 한 방향`이지만 `근본적인 해결은 아직`

<center><img src='Image/Expert/Restricted_Boltzmann_Machine.png' width='600'></center>